# Generated by Django 5.2 on 2025-05-19 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crumbs', '0001_initial'),
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='likedcrumb',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='savedcrumb',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='likedcrumb',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_crumbs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedcrumb',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_crumbs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='likedcrumb',
            constraint=models.UniqueConstraint(fields=('user', 'crumb'), name='unique_liked_crumb'),
        ),
        migrations.AddConstraint(
            model_name='savedcrumb',
            constraint=models.UniqueConstraint(fields=('user', 'crumb'), name='unique_saved_crumb'),
        ),
        migrations.AddField(
            model_name='comment',
            name='crumb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crumbs.crumb'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
