# Generated by Django 5.2 on 2025-06-08 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crumbs', '0002_crumb_tags'),
        ('feedback', '0002_comment_alter_likedcrumb_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='likedcrumb',
            name='crumb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='crumbs.crumb'),
        ),
        migrations.AlterField(
            model_name='savedcrumb',
            name='crumb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='crumbs.crumb'),
        ),
    ]
