# Generated by Django 5.2 on 2025-05-23 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('crumbs', '0001_initial'),
        ('feedback', '0002_comment_alter_likedcrumb_unique_together_and_more'),
        ('preferences', '0003_alter_topic_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_history', models.ManyToManyField(blank=True, to='feedback.comment')),
                ('saved_crumbs', models.ManyToManyField(blank=True, to='crumbs.crumb')),
                ('topic_preferences', models.ManyToManyField(blank=True, to='preferences.topic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
