# Generated by Django 5.2 on 2025-06-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_alter_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
