# Generated by Django 5.2 on 2025-05-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='expires_at',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
