# Generated by Django 5.2 on 2025-06-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_usersubscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
