# Generated by Django 5.2 on 2025-06-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crumbs', '0002_crumb_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crumb',
            name='source',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='crumb',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='crumb',
            name='url',
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
